# https://github.com/veracrypt/VeraCrypt
---

- dynamic_defaults:
    hostvars: '{{ hostvars[inventory_hostname] }}'
    defaults: '{{ veracrypt_dynamic_defaults }}'
    must_match: true
  tags: [veracrypt, always]

- block:
    - name: Install VeraCrypt build packages
      ansible.builtin.package:
        name: '{{ veracrypt_build_packages }}'
        state: present

    - name: Clone VeraCrypt source code
      ansible.builtin.git:
        repo: '{{ veracrypt_repository_url }}'
        dest: '{{ local_source_directory }}/veracrypt'
        force: true
        version: '{{ veracrypt_version }}'

    - name: Build VeraCrypt from source
      ansible.builtin.make:
        chdir: '{{ local_source_directory }}/veracrypt/src'
        params:
          '--jobs': '{{ ansible_processor_cores }}'

    - name: Create VeraCrypt symlink
      ansible.builtin.file:
        src: '{{ local_source_directory }}/veracrypt/src/Main/veracrypt'
        dest: /usr/local/bin/veracrypt
        state: link
  become: true
  tags: [veracrypt, packages]

...
